### ISSUE TITLE
mb_strcut() undefined

### ISSUE THREAD

**Issue by voorsboy** [giggsey/libphonenumber-for-php#217] opened 2017-12-10 15:13 UTC
So, having a very strange error _only_ in production that has been been brought to my attention...

Example:

`[2017-12-10 14:54:05] production.ERROR: Call to undefined function libphonenumber\mb_strcut() (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function libphonenumber\\mb_strcut() at /var/www/html/site/vendor/giggsey/libphonenumber-for-php/src/Matcher.php:72)`

However, mb_strcut() works and I have mbstring enabled/installed. I even tried running `function_exists('mb_strcut')` and it returns true. 

Any ideas? This is only happening on Ubuntu 16.04 and seems to not have any issue in my development environment (win10 x64).

**Comment by xpetter** [comment] 2017-12-14 08:50
I received this error when I upgraded to PHP 7.2, So I downgraded to PHP 7.1 and it solved the problem.

**Comment by xpetter** [comment] 2017-12-14 09:39
I found a solution thet works for me.
Make sure that extension mbstring is loaded in PHP.
https://secure.php.net/manual/en/mbstring.installation.php

**Comment by giggsey** [comment] 2017-12-15 17:54
@voorsboy Are you able to provide some simple example code that triggers this error, along with the PHP version you are running in your production environment.

@xpetter Glad you managed to solve it. I recommend running composer update with the same PHP version/extensions are your production environment, as this would have caught the lack of the mbstring extension.

**Comment by voorsboy** [comment] 2017-12-16 16:22
@giggsey I could not narrow it down to be reproducible. So, I just migrated the server environment to centOS 7.4 as the previous guy had it on Ubuntu. Everything's working now. 

I was just using basic functionality in a Laravel 5.5 application, PHP 7.2 with the proper extensions enabled.

**Comment by giggsey** [comment] 2017-12-20 18:39
@voorsboy Glad you managed to get your code working.

I'm going to close this issue for now, as it doesn't appear to be an issue with this library. If you are able to reproduce this issue, please reopen.

**Closed by giggsey** 2017-12-20 18:39 UTC
