### ISSUE TITLE
Getting empty object

### ISSUE THREAD

**Issue by bluethefish** [giggsey/libphonenumber-for-php#133] opened 2016-10-02 15:07 UTC
$phoneNumberUtil = \libphonenumber\PhoneNumberUtil::getInstance();
            $phoneNumberObject = $phoneNumberUtil->parse('0117 496 0123', 'GB');

            return $phoneNumberObject;

I always getting a empty object.

**Comment by giggsey** [comment] 2016-10-02 15:12
I'm unable to reproduce this.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$phoneNumberUtil = \libphonenumber\PhoneNumberUtil::getInstance();

$phoneNumberObj = $phoneNumberUtil->parse('0117 396 0123', 'GB');

var_dump($phoneNumberObj);

```

> object(libphonenumber\PhoneNumber)#5 (9) {
  ["countryCode":protected]=>
  int(44)
  ["nationalNumber":protected]=>
  string(10) "1173960123"
  ["extension":protected]=>
  NULL
  ["italianLeadingZero":protected]=>
  NULL
  ["rawInput":protected]=>
  NULL
  ["countryCodeSource":protected]=>
  NULL
  ["preferredDomesticCarrierCode":protected]=>
  NULL
  ["hasNumberOfLeadingZeros":protected]=>
  bool(false)
  ["numberOfLeadingZeros":protected]=>
  int(1)
}

**Comment by bluethefish** [comment] 2016-10-02 15:16
I'm using laravel 5.2 and installed the package via composer so this I think it add automatic 
require __DIR__ . '/vendor/autoload.php';  to my code, Im not quite sure kinda new for laravel.
any how I can print here the controller it very basic only for testing this package.

**Comment by giggsey** [comment] 2016-10-02 15:19
Okay, if you are using Laravel, it would already be handling the autoloading.

Instead of returning the PhoneNumber object in your controller, try using the `dd` function. This debug's and dies (a fancy var_dump).

**Comment by bluethefish** [comment] 2016-10-02 15:43
k 10x working like a charm.

**Comment by giggsey** [comment] 2016-10-02 16:32
Cool, is it okay for me to close this issue?

**Comment by giggsey** [comment] 2016-10-03 08:38
_Closing issue, if you have any more questions, please reopen_

**Closed by giggsey** 2016-10-03 08:38 UTC

**Comment by giggsey** [comment] 2016-10-04 08:04
I'm not really sure, and it's outside of the direct scope of this project.

Take a look at https://github.com/Propaganistas/Laravel-Phone, this might cover your usecase.

**Comment by bluethefish** [comment] 2016-10-04 10:52
this repo is extends from your repo?

2016-10-04 11:04 GMT+03:00 Joshua Gigg <notifications@github.com>:

**Comment by giggsey** [comment] 2016-10-04 10:53
It provides Laravel integration with this library.

**Comment by bluethefish** [comment] 2016-10-04 10:54
excellent, 10x for the help !

2016-10-04 13:53 GMT+03:00 Joshua Gigg <notifications@github.com>:

> It provides Laravel integration with this library.
>
